from scrapers import *


def main() -> None:
    ai.main()
    blinky.main()
    bostik.main()
    cfol.main()
    clc.main()
    east.main()
    fpd.main()
    hc.main()
    hs.main()
    inspire.main()
    jjs.main()
    led.main()
    lightem.main()
    livermore.main()
    ll.main()
    lotn.main()
    magical.main()
    mwm.main()
    og.main()
    ppd.main()
    pps.main()
    psp.main()
    rgbsequences.main()
    sa.main()
    sd.main()
    sequence_solutions.main()
    showtime.main()
    sl.main()
    ss.main()
    ssequence.main()
    visionarylightshows.main()
    wls.main()
    xl.main()
    xtreme.main()
    ss.main()
    print("Scraping complete.")



if __name__ == "__main__":
    main()
