"""Sequence table unique constraint

Revision ID: 1587562fefe2
Revises: c0313e8ec7a7
Create Date: 2022-04-02 15:20:41.574581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1587562fefe2'
down_revision = 'c0313e8ec7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.create_unique_constraint('sequence_seq_store_idx', ['vendor_id', 'name', 'link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_constraint('sequence_seq_store_idx', type_='unique')

    # ### end Alembic commands ###
