"""Removed old date strings

Revision ID: 77fdfbc43629
Revises: 7d4ececd02b6
Create Date: 2022-04-02 16:21:58.205944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fdfbc43629'
down_revision = '7d4ececd02b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_column('first_seen')
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('first_seen', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
