"""Add column to track price changes

Revision ID: 82e2fa47e97f
Revises: f38b854cb661
Create Date: 2022-05-06 14:52:55.885826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e2fa47e97f'
down_revision = 'f38b854cb661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_price_changed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('time_price_changed')

    # ### end Alembic commands ###
