BEGIN TRANSACTION;
INSERT INTO "vendor" VALUES (6,'BlinkySequences');
INSERT INTO "vendor" VALUES (7,'PixelPerfectSequences');
INSERT INTO "vendor" VALUES (8,'BostikFamilyLightshow');
INSERT INTO "vendor" VALUES (9,'CFOLights');
INSERT INTO "vendor" VALUES (10,'RGBSequences');
INSERT INTO "vendor" VALUES (11,'SequenceSol');
INSERT INTO "vendor" VALUES (12,'ShowStoppers');
INSERT INTO "vendor" VALUES (13,'VisionaryLightShow');
INSERT INTO "vendor" VALUES (14,'GoogleDrive');
INSERT INTO "vendor" VALUES (15,'Animated Illumination');
INSERT INTO "vendor" VALUES (16,'Custom Light Creations');
INSERT INTO "vendor" VALUES (17,'Fairy Pixel Dust');
INSERT INTO "vendor" VALUES (18,'HolidayCoro');
INSERT INTO "vendor" VALUES (19,'Holiday Sequences');
INSERT INTO "vendor" VALUES (20,'Inspire Lightshows');
INSERT INTO "vendor" VALUES (21,'Jolly Jingle Sequences');
INSERT INTO "vendor" VALUES (22,'Laredo Lights');
INSERT INTO "vendor" VALUES (23,'Led Warehouse');
INSERT INTO "vendor" VALUES (24,'LightEm Up Sequences');
INSERT INTO "vendor" VALUES (25,'Lights of the Night');
INSERT INTO "vendor" VALUES (26,'Livermore Lights');
INSERT INTO "vendor" VALUES (27,'Magical Light Shows');
INSERT INTO "vendor" VALUES (28,'Music with Motion');
INSERT INTO "vendor" VALUES (29,'OG Sequences');
INSERT INTO "vendor" VALUES (30,'Pixel Pro Displays');
INSERT INTO "vendor" VALUES (31,'Sequence Depot');
INSERT INTO "vendor" VALUES (32,'Show Sequences');
INSERT INTO "vendor" VALUES (33,'Syracuse Lights');
INSERT INTO "vendor" VALUES (34,'The Sequence Armory');
INSERT INTO "vendor" VALUES (35,'LED Warehouse');
INSERT INTO "vendor" VALUES (36,'Whimsical Light Shows');
INSERT INTO "vendor" VALUES (37,'xTreme Sequences');
INSERT INTO "vendor" VALUES (38,'xLightsSequences');
INSERT INTO "vendor" VALUES (39,'Showtime Bumpers');
INSERT INTO "vendor" VALUES (40,'East Ridge Lights');
COMMIT;
